export const gitAuth = {
  avatar_url: "https://avatars2.githubusercontent.com/u/17465565?v=4",
  bio: "Hi everyone, I am Roman. I pretty much love building stuff from the ground up, or, working on existing projects; though the former is my favorite. bool",
  blog: "http://www.romanjoran.tk",
  company: "@lambdaschools -- Student",
  created_at: "2016-02-25T03:01:29Z",
  email: "rjordan1352@gmail.com",
  events_url: "https://api.github.com/users/Roman-Jordan/events{/privacy}",
  followers: 30,
  followers_url: "https://api.github.com/users/Roman-Jordan/followers",
  following: 37,
  following_url: "https://api.github.com/users/Roman-Jordan/following{/other_user}",
  gists_url: "https://api.github.com/users/Roman-Jordan/gists{/gist_id}",
  gravatar_id: "",
  hireable: true,
  html_url: "https://github.com/Roman-Jordan",
  id: 17465565,
  location: "Vancouver, Washington",
  login: "Roman-Jordan",
  name: "Roman Jordan",
  node_id: "MDQ6VXNlcjE3NDY1NTY1",
  organizations_url: "https://api.github.com/users/Roman-Jordan/orgs",
  public_gists: 4,
  public_repos: 107,
  received_events_url: "https://api.github.com/users/Roman-Jordan/received_events",
  repos_url: "https://api.github.com/users/Roman-Jordan/repos",
  site_admin: false,
  starred_url: "https://api.github.com/users/Roman-Jordan/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/Roman-Jordan/subscriptions",
  token: "TOKEN",
  type: "User",
  updated_at: "2019-10-26T05:41:51Z",
  url: "https://api.github.com/users/Roman-Jordan"
};

export const googleAuth ={
    email: "romanjordan255@gmail.com",
    email_verified: true,
    family_name: "Jordan",
    given_name: "Roman",
    locale: "en",
    name: "Roman Jordan",
    picture: "https://lh3.googleusercontent.com/-ASaY0SANelo/AAAAAAAAAAI/AAAAAAAAAAA/ACHi3rdokkdjrZohTqzdndENxux0gLpnug/photo.jpg",
    sub: "118064446743336738788"
}
